version: '3'

tasks:
  default:
    desc: Build CLI binary and run tests
    cmds:
      - task: check

  build:
    desc: Build slimvu CLI executable
    cmds:
      - go build -o bin/slimvu ./cmd/slimvu

  install:
    desc: Install slimvu CLI executable to GOBIN / $GOPATH/bin
    cmds:
      - go install ./cmd/slimvu

  test:
    desc: Run unit and integration tests with race detector
    cmds:
      - go test -v -race ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  tidy:
    desc: Clean up and verify go.mod
    cmds:
      - go mod tidy

  check:
    desc: Run all checks (tidy, vet, test, build)
    cmds:
      - task: tidy
      - task: vet
      - task: test
      - task: build
